/**
 * Created by jjohnson on 12/9/13.
 * Edited by kevin.he on 10/29/2014, categories are correct as of this date
 * 
 */
var NetworkAbstraction = require('./NetworkAbstraction.js');

module.exports = OktaAPI;
OktaAPI.Helpers = require('./OktaHelpers.js');
/**
 * Instantiate a new Okta API session with the given API token
 * @param apiToken
 * @param domain
 * @param preview
 * @constructor
 */
function OktaAPI(apiToken, domain, preview) {
    if(apiToken == undefined || domain == undefined) {
        throw new Error("OktaAPI requires an API token and a domain");
    }
    this.domain = domain;
    if(preview == undefined) this.preview = false;
    else this.preview = preview;
    this.request = new NetworkAbstraction(apiToken, domain, preview);
}


/*******************************************************************
************************ Users->UserOps Start **********************
********************************************************************
*/
/*
 * Okta User Documentation
 * http://developer.okta.com/docs/api/rest/users.html
 */
/**
 * Gets a list of users in your Okta
 * @method getUsers
 * @param search an object with search parameters in this format: {q: <query>, limit: <int>, filter: <filter>, after: <cursor>}
 *          more docs can be found on the Okta User Endpoint documentation
 * @param callback
 */
OktaAPI.prototype.getUsers = function(search, callback) {
    this.request.get("users", search, callback);
}
/**
 * Searches your Okta for a specific user
 * @method getUser
 * @param who search query
 * @param callback
 */
OktaAPI.prototype.getUser = function(who, callback) {
    if(who == undefined) throw new Error("A search query is required when trying to get a user from Okta");
    this.request.get("users/" + who, null, callback);
}
/**
 * Provisions a user to your Okta
 * @method addUser
 * @param profile a profile object, usually generated by OktaAPI.Helpers.constructProfile()
 * @param credentials a credentials object, usually generated by OktaAPI.Helpers.constructCredentials()
 * @param activate whether or not to fully activate this account
 * @param callback
 */
OktaAPI.prototype.addUser = function(profile, credentials, activate, callback) {
    if(profile == undefined) throw new Error("Profile is required when adding a user to Okta");
    var body = {profile: profile};
    if(credentials) body.credentials = credentials;
    var qs = {activate: activate};
    this.request.post("users", body, qs, callback);
}
/**
 * Update a user's profile
 * @method updateUser
 * @param id id of the user to update
 * @param profile the new, complete profile of this user
 * @param credentials the new, complete credentials of this user
 * @param callback
 */
OktaAPI.prototype.updateUser = function(id, profile, credentials, callback) {
    if(id == undefined) throw new Error("A user ID is required when updating a user in Okta");
    var body = {};
    if(credentials) body.credentials = credentials;
    if(profile) body.profile = profile;
    this.request.put("users/" + id, body, null, callback);
}

/*******************************************************************
************************ Users->UserOps End ************************
********************************************************************
*/


/*******************************************************************
****************** Users->Related Resources Start ******************
********************************************************************
*/

/**
 * Get the apps that this user has on their dashboard
 * @method getAppLinks
 * @param id id of the user
 * @param callback
 */
OktaAPI.prototype.getAppLinks = function(id, callback) {
    if(id == undefined) throw new Error("A user ID is required when requesting app links from Okta");
    this.request.get("users/" + id + "/appLinks", null, callback);
}
/**
 * get the groups that this user is in
 * @method getMemberGroups
 * @param id
 * @param callback
 */
OktaAPI.prototype.getMemberGroups = function(id, callback) {
    if(id == undefined) throw new Error("A user ID is required when requesting a user's groups");
    this.request.get("users/" + id + "/groups", null, callback);
}

/*******************************************************************
****************** Users->Related Resources End ********************
********************************************************************
*/

/*******************************************************************
**************** Users->Lifecycle Operations Start *****************
********************************************************************
*/

/**
 * fully activate a user
 * @method activateUser
 * @param id the ID of the user
 * @param sendEmail whether or not to send the activation e-mail
 * @param callback
 */
OktaAPI.prototype.activateUser = function(id, sendEmail, callback) {
    if(id == undefined) throw new Error("A user ID is required when activating a user");
    if(sendEmail == undefined) throw new Error();
    var queryObj = {sendEmail: sendEmail};
    this.request.post("users/" + id + "/lifecycle/activate", null, queryObj, callback);
}
/**
 * deactivate a user; destructively deprovisioning all their accounts
 * @method deactivateUser
 * @param id
 * @param callback
 */
OktaAPI.prototype.deactivateUser = function(id, callback) {
    if(id == undefined) throw new Error("A user ID is required when deactivating a user");
    this.request.post("users/" + id + "/lifecycle/deactivate", null, null, callback);
}
/**
 * Nullify a lockout from too many failed passwords
 * @method unlockUser
 * @param id
 * @param callback
 */
OktaAPI.prototype.unlockUser = function(id, callback) {
    if(id == undefined) throw new Error("A user ID is required when unlocking a user");
    this.request.post("/users/" + id + "/lifecycle/unlock", null, null, callback);
}
/**
 * Have Okta generate a one-time-token for a password reset
 * @method resetPassword
 * @param id
 * @param sendEmail send an email with the reset token
 * @param callback
 */
OktaAPI.prototype.resetPassword = function(id, sendEmail, callback) {
    if(id == undefined) throw new Error("A user ID is required when resetting a users password");
    if(sendEmail == undefined) throw new Error();
    var queryObj = {sendEmail: sendEmail};
    this.request.post("users/" + id + "/lifecycle/reset_password", null, queryObj, callback);
}
/**
 * Forces user to change thier password on next login
 * @method resetPassword
 * @param id
 * @param tempPassword response will contain temp password
 * @param callback
 */
OktaAPI.prototype.expirePassword = function(id, tempPassword, callback) {
    if(id == undefined) throw new Error("A user ID is required when expiring a users password");
    var queryObj;
    if(tempPassword == undefined) 
    {
        queryObj = null;
    }
    else
    {
        queryObj = {tempPassword : tempPassword};
    }
    this.request.post("users/" + id + "/lifecycle/expire_password", null, queryObj, callback);
}
/**
 * Forces user to change thier password on next login
 * @method resetPassword
 * @param id
 * @param callback
 */
OktaAPI.prototype.resetFactors = function(id, callback) {
    if(id == undefined) throw new Error("A user ID is required when resetting a user's MFA stuff");
    this.request.post("users/" + id + "/lifecycle/reset_factors", null, null, callback);
}


/*******************************************************************
**************** Users->Lifecycle Operations End *******************
********************************************************************
*/


/*******************************************************************
*************** Users->Credential Operations Start *****************
********************************************************************
*/

/**
 * Have Okta generate a one-time-token for the forgotten password flow (requires security question)
 * @method forgotPassword
 * @param id
 * @param sendEmail
 * @param callback
 */
OktaAPI.prototype.forgotPassword = function(id, sendEmail, callback) {
    if(id == undefined) throw new Error("A user ID is required when triggering a forgotten password flow");
    if(sendEmail == undefined) throw new Error();
    var queryObj = {sendEmail: sendEmail};
    this.request.post("users/" + id + "/lifecycle/forgot_password", null, queryObj, callback);
}
/**
 * Sets a new password for a user by validating the recoveryQuestionObj against Okta
 * @method attemptResetPassword
 * @param id
 * @param passwordObj
 * @param recoveryQuestionObj
 * @param callback
 */
OktaAPI.prototype.attemptResetPassword = function(id, passwordObj, recoveryQuestionObj, callback) {
    if(id == undefined) throw new Error("A user ID is required when resetting a users password");
    if(passwordObj == undefined) throw new Error("A new password is required to reset a users password");
    if(recoveryQuestionObj == undefined) throw new Error("A security answer is required while resetting a users password");
    var body = {};
    body.password = passwordObj;
    body.recovery_question = recoveryQuestionObj;
    this.request.post("users/" + id + "/credentials/forgot_password", body, null, callback);
}
/**
 * Validates the provided password against Okta and changes it to the new password
 * @method attemptChangePassword
 * @param id
 * @param oldPasswordObj
 * @param newPasswordObj
 * @param callback
 */
OktaAPI.prototype.attemptChangePassword = function(id, oldPasswordObj, newPasswordObj, callback) {
    if(id == undefined) throw new Error("A user ID is required when changing a users password");
    if(oldPasswordObj == undefined) throw new Error("A current password object is required when resetting a users password");
    if(newPasswordObj == undefined) throw new Error("A new password object is required when changing a users password");
    var body = {};
    body.oldPassword = oldPasswordObj;
    body.newPassword = newPasswordObj;
    this.request.post("users/" + id + "/credentials/change_password", body, null, callback);
}
/**
 * Validates the provided password against Okta and changes the recovery question
 * @method attemptChangeRecoveryQuestion
 * @param id
 * @param passwordObj
 * @param recoveryQuestionObj
 * @param callback
 */
OktaAPI.prototype.attemptChangeRecoveryQuestion = function(id, passwordObj, recoveryQuestionObj, callback) {
    if(id == undefined) throw new Error("A user ID is required when changing a users recovery questions");
    if(passwordObj == undefined) throw new Error("A current password object is required when changing a users recovery question");
    if(recoveryQuestionObj == undefined) throw new Error("A recovery question object is required when changing a users recovery question");
    var body = {};
    body.password = passwordObj;
    body.recovery_question = recoveryQuestionObj;
    this.request.post("users/" + id + "/credentials/change_recovery_question", body, null, callback);
}

/*******************************************************************
*************** Users->Credential Operations End *******************
********************************************************************
*/


/*******************************************************************
***************** Groups->Group Operations Start *******************
********************************************************************
*/
/*
 * Okta Group Documentation
 * http://developer.okta.com/docs/api/rest/groups.html
 */
/**
 * Add a new group to Okta
 * @method addGroup
 * @param groupProfile a group profile object, normally constucted with OktaAPI.Helpers.constructGroup()
 * @param callback
 */
OktaAPI.prototype.addGroup = function(groupProfile, callback) {
    if(groupProfile == undefined) throw new Error("A group profile is required when creating a group");
    var body = {};
    body.profile = groupProfile;
    this.request.post("groups", body, null, callback);
}
/**
 * @method getGroups
 * @param search
 * @param callback
 */
OktaAPI.prototype.getGroups = function(search, callback) {
    var queryObj = {};
    if(search != undefined) queryObj = search;
    this.request.get("groups", queryObj, callback);
}
/**
 * @method getGroup
 * @param groupId
 * @param callback
 */
OktaAPI.prototype.getGroup = function(groupId, callback) {
    if(groupId == undefined) throw new Error("A group ID is required when getting a group");
    this.request.get("groups/" + groupId, null, callback);
}
/**
 * Update the group's profile.
 * @method updateGroup
 * @param groupId
 * @param groupObj the complete group object, normally constructed with OktaAPI.Helpers.constructGroup()
 * @param callback
 */
OktaAPI.prototype.updateGroup = function(groupId, groupObj, callback) {
    if(groupId == undefined) throw new Error("A group ID is required when updating a group");
    if(groupObj == undefined) throw new Error("A group object is required when updating a group");
    var body = {profile: groupObj};
    this.request.put("groups/" + groupId, body, null, callback);
}
/**
 * Deletes a group from Okta (note: returns no response if successful)
 * @method deleteGroup
 * @param groupId
 * @param callback
 */
OktaAPI.prototype.deleteGroup = function(groupId, callback) {
    if(groupId == undefined) throw new Error("A group ID is required when updating a group");
    this.request.delete("groups/" + groupId, null, callback);
}

/*******************************************************************
***************** Groups->Group Operations End *********************
********************************************************************
*/

/*******************************************************************
************ Groups->Group Member Operations Start *****************
********************************************************************
*/

/**
 * Get a list of users in the group
 * @method getUsersInGroup
 * @param groupId
 * @param callback
 */
OktaAPI.prototype.getUsersInGroup = function(groupId, queryObj, callback) {
    if(groupId == undefined) throw new Error("A group ID is required when fetching users in a group");
    this.request.get("groups/" + groupId + "/users", queryObj, callback);
}
/**
 * @method addUserToGroup
 * @param groupId
 * @param userId
 * @param callback
 */
OktaAPI.prototype.addUserToGroup = function(groupId, userId, callback) {
    if(groupId == undefined) throw new Error("A group ID is required to add a user to a group");
    if(userId == undefined) throw new Error("A user ID is required to add a user to a group");
    this.request.put("groups/" + groupId + "/users/" + userId, null, null, callback);
}
/**
 * @method removeUserFromGroup
 * @param groupId
 * @param userId
 * @param callback
 */
OktaAPI.prototype.removeUserFromGroup = function(groupId, userId, callback) {
    if(groupId == undefined) throw new Error("A group ID is required to remove a user from a group");
    if(userId == undefined) throw new Error("A user ID is required to remove a user from a group");
    this.request.delete("groups/" + groupId + "/users/" + userId, null, callback);
}


/*******************************************************************
************ Groups->Group Member Operations End *******************
********************************************************************
*/

/*******************************************************************
**************** Groups->Related Resources Start *******************
********************************************************************
*/

/**
 * @method getAppsForGroup
 * @param groupId
 * @param search
 * @param callback
 */
OktaAPI.prototype.getAppsForGroup = function(groupId, search, callback) {
    if (groupId == undefined) throw new Error("A group ID is required when getting apps for a group");
    this.request.get("groups/" + groupId + "/apps", search, callback);
}

/*******************************************************************
***************** Groups->Related Resources End ********************
********************************************************************
*/



/*******************************************************************
*************** Session->Session Operations Start ******************
********************************************************************
*/
/*
 * Okta Sessions Documentation
 * http://developer.okta.com/docs/api/rest/sessions.html
 */

/**
 * @method createSession
 * @param user
 * @param pass
 * @param additionalFields
 * @param callback
 */
OktaAPI.prototype.createSession = function(user, pass, additionalFields, callback) {
    if(user == undefined) throw new Error("A username is required when making a new session");
    if(pass == undefined) throw new Error("A password is required when making a new session");
    var queryObj = {};
    if(additionalFields != undefined) queryObj.additionalFields = additionalFields;
    var body = {};
    body.username = user;
    body.password = pass;
    this.request.post("sessions", body, queryObj, callback);
}
/**
 * @method validateSession
 * @param sessionId
 * @param callback
 */
OktaAPI.prototype.validateSession = function(sessionId, callback) {
    if(sessionId == undefined) throw new Error("A session ID is required when validating a session");
    this.request.get("sessions/" + sessionId, null, callback);
}
/**
 * @method extendSession
 * @param sessionId
 * @param callback
 */
OktaAPI.prototype.extendSession = function(sessionId, callback) {
    if(sessionId == undefined) throw new Error("A session ID is required when extending a session");
    this.request.put("sessions/" + sessionId, null, null, callback);
}
/**
 * @method closeSession
 * @param sessionId
 * @param callback
 */
OktaAPI.prototype.closeSession = function(sessionId, callback) {
    if(sessionId == undefined) throw new Error("A session ID is required when closing a session");
    this.request.delete("sessions/" + sessionId, null, callback);
}

/*******************************************************************
**************** Session->Session Operations End *******************
********************************************************************
*/

/*******************************************************************
*************** Apps->Application Operations Start *****************
********************************************************************
*/

/*
 * Okta Applications Documentation
 * http://developer.okta.com/docs/api/rest/apps.html
 */
 /**
  * @method addApplication
  * @param appModel an app model per Okta docs
  * @param callback
  */
 OktaAPI.prototype.addApplication = function(appModel, callback) {
    if(appModel == undefined) throw new Error("An application model is required when adding an application");
    this.request.post("apps", appModel, null, callback);
 }

/**
 * @method getApplication
 * @param id an application ID to get
 * @param callback
 */
 OktaAPI.prototype.getApplication = function(id, callback) {
    if(id == undefined) throw new Error("An application ID is required when getting an application");
    this.request.get("apps/" + id, null, callback);
 }

/**
 * @method getApplications
 * @param filter a string search for which apps to return; refer to Okta docs
 * @param callback - paged response; callback can be called several times
 */
 OktaAPI.prototype.getApplications = function(params, callback) {
    var queryObj = {};
    if(params != undefined) queryObj = params;
    this.request.get("apps", queryObj, callback);
 }

 /**
  * @method updateApplication
  * @param id
  * @param profile
  */
OktaAPI.prototype.updateApplication = function(id, profile, callback) {
    if(id == undefined) throw new Error("An application ID is required when updating an application");
    if(profile == undefined) throw new Error("An application profile is required when updating an application");
    this.request.put("apps/" + id, profile, null, callback);
}

/**
 * @method deleteApplication removes a deactivated application
 * @param id
 * @param callback
 */
OktaAPI.prototype.deleteApplication = function(id, callback) {
    if(id == undefined) throw new Error("An application ID is required when deleting an application");
    this.request.delete("apps/" + id, null, callback);
}

/**
 * @method activateApplication
 * @param id
 * @param callback
 */
OktaAPI.prototype.activateApplication = function(id, callback) {
    if(id == undefined) throw new Error("An application ID is required when activating an application");
    this.request.post("apps/" + id + "/lifecycle/activate", null, null, callback);
}

/**
 * @method deactivateApplication
 * @param id
 * @param callback
 */
OktaAPI.prototype.deactivateApplication = function(id, callback) {
    if(id == undefined) throw new Error("An application ID is required when deactivating an application");
    this.request.post("apps/" + id + "/lifecycle/deactivate", null, null, callback);
}


/*******************************************************************
**************** Apps->Application Operations End ******************
********************************************************************
*/


/*******************************************************************
************ Apps->Application User Operations Start ***************
********************************************************************
*/

OktaAPI.prototype.assignUserToApplication = function(appId, appUserModel, callback) {
    if(appId == undefined) throw new Error("An application Id is required when assigning a user to an application");
    if(appUserModel == undefined) throw new Error("An Application User is required when assigning a user to an application");
    this.request.post("apps/" + appId + "/users", appUserModel, null, callback);
}



OktaAPI.prototype.getAssignedUserForApplication = function(appId, uid, callback) {
    if(appId == undefined) throw new Error("An application Id is required when getting an assigned user for an application");
    if(uid == undefined) throw new Error("A user ID is required when getting an assigned user for an application");
    this.request.get("apps/" + appId + "/users/" + uid, null, callback);
}

OktaAPI.prototype.getUsersAssignedToApplication = function(id, callback) {
    if(id == undefined) throw new Error("An application ID is required when getting a list of users assigned to an application");
    this.request.get("apps/" + id + "/users", null, callback);
}

OktaAPI.prototype.updateCredsForApplication = function(aid, uid, appUserModel, callback) {
    // TODO: abstract the appUserModel
    if(aid == undefined) throw new Error("An application ID is required when updating creds for an application");
    if(uid == undefined) throw new Error("A user ID is required when updating creds for an application");
    //throw new Error("Not yet implemented"); // this is intentional. Uncomment if you wish to use this call w/o abstracted user models
    this.request.post("apps/" + aid + "/users/" + uid, appUserModel, null, callback);
}


OktaAPI.prototype.updateProfileForApplication = function(aid, uid, appUserModel, callback) {
    // TODO: abstract the appUserModel
    if(aid == undefined) throw new Error("An application ID is required when updating the profile for an application");
    if(uid == undefined) throw new Error("A user ID is required when updating the profile for an application");
    //throw new Error("Not yet implemented"); // this is intentional. Uncomment if you wish to use this call w/o abstracted user models
    this.request.post("apps/" + aid + "/users/" + uid, appUserModel, null, callback);
}

OktaAPI.prototype.removeUserFromApplication = function(aid, uid, callback) {
    if(aid == undefined) throw new Error("An application ID is required when removing a user from an app");
    if(uid == undefined) throw new Error("A user ID is required when removing a user from an app");
    this.request.delete("apps/ " + aid + "/users/" + uid, null, callback);
}



/*******************************************************************
************* Apps->Application User Operations End ****************
********************************************************************
*/

/*******************************************************************
*********** Apps->Application Group Operations Start ***************
********************************************************************
*/

OktaAPI.prototype.assignApplicationToGroup = function(aid, gid, callback) {
    // TODO: there is an optional "appgroup" param. Figure out what it does and how to use it.
    if(aid == undefined) throw new Error("An application ID is required when assigning an application to a group");
    if(gid == undefined) throw new Error("A group ID is required when assigning an application to a group");
    this.request.put("apps/" + aid + "/groups/" + gid, {}, null, callback);
}

OktaAPI.prototype.getGroupAssignedToApplication = function(aid, gid, callback) {
    if(aid == undefined) throw new Error("Application ID is required when getting a group assigned to an application");
    if(gid == undefined) throw new Error("A group ID is required when getting a group assigned to an application");
    this.request.get("apps/" + aid + "/groups/" + gid, null, callback);
}

OktaAPI.prototype.getGroupsAssignedToApplication = function(aid, queryObj, callback) {
    if(aid == undefined) throw new Error("An application ID is required when getting the groups assigned to an application");
    this.request.get("apps/" + aid + "/groups", queryObj, callback);
}

OktaAPI.prototype.removeGroupFromApplication = function(aid, gid, callback) {
    if(aid == undefined) throw new Error("An application ID is required when unassigning an application to a group");
    if(gid == undefined) throw new Error("A group ID is required when unassigning an application to a group");
    this.request.delete("apps/" + aid + "/groups/" + gid, null, null, callback);
}



/*******************************************************************
***************** Events->Event Operations Start *******************
********************************************************************
*/

/*
 * Okta Events Endpoint
 * http://developer.okta.com/docs/api/rest/events.html
 */
/**
 * @method getEvents
 * @param filter
 * @param limit
 * @param startDate
 * @param callback
 */
OktaAPI.prototype.getEvents = function(queryObj, callback) {
    this.request.get("events", queryObj, callback);
}


/*******************************************************************
***************** Events->Event Operations End *********************
********************************************************************
*/


/*
 * Helpers and wrappers
 */
/**
 * Performs a partial update on a user's profile
 * @method updateUserPartial
 * @param userId
 * @param partialProfile partial profile info; or null to update password
 * @param partialCredentials partial credentials info; or null to only update profile
 * @param callback
 */
OktaAPI.prototype.updateUserPartial = function(userId, partialProfile, partialCredentials, callback) {
    if(userId == undefined) throw new Error("A user ID is required");
    var that = this;
    this.getUser(userId, function(d) {
        if(!d.success || d.resp.errorCode) {
            callback({success: false, error: "Failed to retrieve user", resp: d.resp});
            return;
        }
        mergeProfiles(that, d.resp, partialProfile, partialCredentials, callback);
    });
}

/*
 * Private methods
 */
function mergeProfiles(what, userObj, updateProf, updateCreds, callback) {
    var finalProfile, finalCreds;
    if(updateProf != undefined) {
        finalProfile = {};
        for(prop in userObj.profile) finalProfile[prop] = userObj.profile[prop];
        for(prop in updateProf) finalProfile[prop] = updateProf[prop];
    }
    if(updateCreds != undefined) {
        finalCreds = {};
        for(prop in userObj.credentials) finalCreds[prop] = userObj.profile[prop];
        for(prop in updateCreds) finalCreds[prop] = updateCreds[prop];
    }
    what.updateUser(userObj.id, finalProfile, finalCreds, function(d) {
        if(!d.success || d.resp.errorCode) {
            callback({success: false, error: "Failed to update user info", resp: d.resp});
            return;
        }
        callback({success: true, resp: d.resp});
    })
}
